# 2. Callback과 Promise

# 1. Callback 함수

 자바스크립트의 일반적인 함수인 callback함수란 이름 그대로 나중에 호출되는 함수이다.  어떤 이벤트가 발생하거나 특정시점에 도달했을 때 시스템에서 호출하는 함수이다.

자세히 들어가면 자바스크립트에서 함수는 object이고, 함수는 다른 함수의 인자나 return 값으로 쓰일 수 있다. 이런 함수를 고차함수(higher-order functions)라 부르고 인자로 넘겨지는 함수를 콜백함수 (callback function) 라고 한다. 

## 1.1 왜 필요한가?

자바스크립트는 이벤트 기반 언어이기 때문이다. 사용자로 부터 받은 요청의 결과를 기다리지 않고 다음 작업을 수행한다. 

아래 예제를 보면 first()를 먼저 실행시켰지만, second()를 먼저 수행 시킨 것으르 볼 수 있다. 이는 자바스크립트가 first()함수로부터의 응답을 기다리지 않고 second()함수를 먼저 실행 시킨다는 것을 알 수 있다. 

따라서 Non-block 이며, 비동기(Asynchronous)방식의 함수로 사용된다는 것을 알 수 있다. 

이는 Node.js의 핵심이다. 

```jsx
function first(){

  setTimeout( function(){
    console.log(1);
  }, 3000);
}

function second(){
  console.log(2);
}

first();
second();

//result 
2
1
```

## 1.2 callback함수 어떻게 쓰지?

우선 하나의 함수를 선언하고 인자값으로 a, b, callback을 받는다. 아래 예시를 보면 알 수 있듯이 callback함수는 a와 b의 연산의 결과를 넣는다.  여기까지는 함수의 기능이며 실제로 사용자가 plus라는 함수에 값을 (5, 10) 을 넣으면 그 결과가 res로 출력한다.

```jsx
plus = function(a, b, callback) {
	
	let result = a + b;
callbaack(result);
}

plus(5,10, function(res) {
console.log(res);
})
```

아래 예시도 동일하다. a,b의 연상 결과를 callback함수에 넣는 함수를 만들어 결과를 넣는다.  

```jsx
plus = function(a, b, callback){
  callback(a+b, a-b);
}
 
plus (5,10, function(res1, res2){
  console.log(res1);
  console.log(res2);
})
```

그러나 이러한 callback을 비동기로 처리하기 위해 무분별하게 callback안에 callback을 작성할 경우 callback지옥이 형성될 수 있다. 이 문제를 해결하기 위해 promose 또는 async/awit를 사용할 수 있다.

# 2. Promise

ES6부터 등장한 흐름제어 패턴으로 내부적으로 예외처리구조 기능을 가진다. 

promise는 하나의 class이다. 

```jsx
new Promise((resolve, reject) => {
    //
});

// resolve()  	// => go to next action
// reject() 	//=> handle error
```

## 2.1 promise 생성방법

promise는 Promise 생성자 함수를 통해 인스턴스(instance)화 된다. Promisse 생성자 함수는 비동기 작업을 수행할 callback 함수를 인자로 전달 받는데, 이 callback함수는 resolve와 reject함수를 인자로 전달 받는다. 

resolve(성공) 시에는 then,  reejct(실패) 시에는 catch가 실행된다.

1. promise를 지원하는 메서드라면 내부적으로 지원해주기 때문에 then과 catch 사용이가능하다.
2. then에 return 값이 있으면 다음 then으로 넘어가고, Promise를 return하면 resolve(성공), reject(실패)되어 넘어간다.

```jsx
// promise 객체생성 
const plus = new Promise((resolve, reject) => {
  // 여기서 비동기 작업을 수행한다.
    const a = 1;
    const b = 2;
    if(a + b > 2){ /* 비동기 작업 수행 성공 */
        resolve (a + b);

    }else{    /* 비동기 작업 수행 실패 */
        reject(a + b);
    }
});
plus
    .then((sucess) => {
 
    })
    .catch((fail) => {
 
    })
```

## 2.2 promise - then / catch

1. **then**

    두개의 callback함수를 인자로 전달 받는다. 

    첫번째 callback함수는 성공할 때 호출되며, 두번째 callback함수는 실패할 때 호출된다

    then 메소드는Promose를 반환한다. 

2. catch

    예외가 발생할 때 호출된다.

    catch 메소드는 Promise를 반환한다. 

## 2.3 callback VS promise

### 1. **Callback**

printString 이라는 함수는 생성하여 string과 callback을 받는다.  그리고 랜덤한 시간 후에 출력하게 하였다. 

printAll이 실행이 되면 1번 pringString이 실행되고 console에 "A"가 찍히고 callback한다.  callback안에는 2번 printString이 있으며 이건 "B"를 출력하고 또 callback한다. callback했더니 또 3번 printString이 있고 "C"를 출력하고 callback함으로 써 마무리 된다. 

```jsx
const printString = (string, callback) => {
  setTimeout(() => {
    console.log(string)
    callback()
  }, Math.floor(Math.random() * 100) + 1);
}

const printAll = () => {
  printString ("A", () => {       // 1번 printString
    printString ("B", () => {       // 2번 printString
      printString ("C", () => {})       // 3번 printString
    })
  })
}
printAll()  

//result
A
B
C
```

### 2. **Promise**

동일하게 printString이라는 함수와 printAll이라는 함수가 있다. printString에는 인자가 들어오면 return을 해준다. 어떤것을? Promise intance를 !! promise 는 resolve(성공)와 reject(실패)를 매개변수로 callback함수에 넣을 수 있다. 여기서는 실패는 없다. 

그럼 사용자는 printAll()을 호출함으로써 실행이 된다. 최로에 printString에 "A" 라는 값을 넣어서 반환을 받는다. 실패는 없으므로 곧바로 then (그러면?) then은 또 아무 인자값 없이 호출받아 printString("B")를 return 하고 또 무사히 성공하므로 return printString("C")를 호출한다.

 결과는 똑같지만 사용자가 보기에 훨씬 더 직관적으로 잘 알 수 있다.  실제로 callback함수 안에 callback함수를 이해하는데 생각보다 많은 시간을 보냈는데, promise의 경우 단번에 이해를 할 수 있었다. 

```jsx
const printString = (string) => {
  return new Promise ((resolve, reject) => {
    setTimeout(() => {
      console.log(string)
      resolve()
    }, Math.floor(Math.random() * 100) + 1);
  })
}

const printAll = () => {
  printString ("A")
  .then(() => {
    return printString("B")
  })
  .then(() => {
    return printString("C")
  })
}
printAll()
```

## 2.4 Promise.all

Promise.all로 여러개의 promise를 동시에 실행 가능하다. 하지만 하나라도 실패하면 catch이며 callback에서는 불가능하다. 

```jsx
Promise.all([Users.findOne(), Users.remove(), Users.update()])
    .then((result) => {})
    .catch((error) => {})
```

## 2.5 상태(state)

![image](https://user-images.githubusercontent.com/63430211/120660661-83de1000-c4c2-11eb-9442-d0a4413bb5e8.png)
